### ISSUE TITLE
Avoid reading package files at runtime

### ISSUE THREAD

**Issue by KristofferC** [beacon-biosignals/StableHashTraits.jl#32]
This package tries to read its readme at initialization time:

https://github.com/beacon-biosignals/StableHashTraits.jl/blob/9def8095355de77f2942a7ddd1592d3dd267ea6c/src/StableHashTraits.jl#L62

This is an issue when using e.g. PackageCompiler with this package because the markdown file might not exist. Also, the `pkgdir` computation will refer to where the package was loaded which won't work if one creates a sysimage on one machine and transfers it to another.

I would suggest either reading this file at precompile time or alternatively having a graceful fallback in case the file does not exist.

**Comment by ericphanson** [comment]
One note is if we read it at precompilation time, we could use `Base.include_dependency` to invalidate the precompilation cache if the readme changes. (Although that could be annoying to wait for precompilation just to update some docstrings)

**Comment by haberdashPI** [comment]
Happy to fix this. 

It appears I'm a little confused about when this line can be executed. I had thought that by doing this outside of __init__ that it would occur at a time when README would have to exist. 

Is a more appropriate way to find the file `joinpath(@__DIR__, "..", "README.md")`?

**Comment by haberdashPI** [comment]
I guess a more germane question than my last point: does moving this code outside init mean that the README.md will always exist?

**Comment by KristofferC** [comment]
Yes because at precompile time we are sure that the files exist.
