### ISSUE TITLE
remove generated functions, or add CI test with `--compiled-modules=no`

### ISSUE THREAD

**Issue by ericphanson** [beacon-biosignals/StableHashTraits.jl#40]
To prevent regression on #36

**Comment by haberdashPI** [comment]
The generated functions make a fair bit of difference, when I was messing around with the benchmarks. Makes sense to add `--compiled-modules=no`.

**Comment by haberdashPI** [comment]
Looking into this a bit, [these lines](https://github.com/julia-actions/julia-runtest/blob/9b1be2f86a0d18e5d5a21629777526780873e0f9/test_harness.jl#L3-L5) lead me to believe that I may need to make a small PR there so that this argument can be added to the test process.
